sudo: required
services:
    - docker
before_install:
    - docker build -t vineet03/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true vineet03/react-test npm test
after_success:
    - docker build -t vineet03/multi-client ./client
    - docker build -t vineet03/multi-nginx ./nginx
    - docker build -t vineet03/multi-server ./server
    - docker build -t vineet03/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push vineet03/multi-client
    - docker push vineet03/multi-nginx
    - docker push vineet03/multi-server
    - docker push vineet03/multi-worker